### ISSUE TITLE
Updates to / comments about project listing 

### ISSUE THREAD

**Issue by rmandelb** [LSSTDESC/desc-publications#10]
Here are my comments on the project list page:

- Does it really make sense to list a project N times if it's associated with N working groups?  I would have thought it should still be one listing, with a lead working group + others identified.

- Is the "Members" column meant to list all members, or just the leads?  I think the project pages should perhaps list all participants, but since the project listing is a summary, it should just list the lead(s).  Perhaps this was the intent, but in that case the column name should be updated.

- It would be useful if there was some way to sort or select by status, e.g., if we want to see all active projects only.

**Comment by abmantz** [comment]
Strangely, I see some of the projects repeated even with the same working group on this page, with the same projid. For e.g., I see "Mass makes waves but no sound" listed 3 times under CL and 3 times under WL, alternating; and similarly "Galaxy shapes" twice under CS and twice under WL. Is this just me?

**Comment by rmandelb** [comment]
You are right - I see it too - I didn't notice that before.  I *think* the issue is that the project has 3 publications x 2 working groups = 6 appearances?  (Which doesn't really make sense as a strategy, but at least that is maybe why it's happening?)  There's another example of this for the Galaxy Shapes project, which shows up 4 times (=2 WGs x 2 publications).

**Comment by chee999** [comment]
I have cleaned up this page so the project name is listed only once with all the associated working groups listed separately. All the columns are sortable. Still working on displaying the project leads.

**Comment by chee999** [comment]
These issues have been resolved in the latest test version.
