### ISSUE TITLE
SRM Research Activity field

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/desc-publications#101]
A follow-up to #95 - see the discussion there, but I think it will be helpful to have separate SRM Deliverable and SRM Research Activity fields in the project definition form, with separate dropdown lists. The activity csv file does not yet exist but can be made straightforwardly - that's an action for me. The activity part of the form would follow straight after the deliverable part, and work the same way, with multiple or zero activities selectable for each project. Then, the pub system will match the [example project template in confluence](https://confluence.slac.stanford.edu/display/LSSTDESC/Example+Project%3A+Make+a+Copy+and+Edit+It) and we'll be helping the collaboration members with their SRM awareness. What do you think, @chee999 ? Is this as easy to set up as I think it should be? :-)

**Comment by sethdigel** [comment]
@chee999 Does what Phil proposes sound doable?  The csv file for Activities would be separate from the one for Deliverables but it would have the same format.  On the Project definition form, the idea would be to change 'SRM activity' to 'SRM Deliverable'.  And to add a similar box with the heading 'SRM Research Deliverable' containing the list of activities read from Phil's to-be-provided csv file.

**Comment by chee999** [comment]
Yes, it's do-able. I'm waiting to see what the data looks like and where to find the csv files.

**Comment by drphilmarshall** [comment]
I will need to do a bit of SRM-scraping work to make this file - or in fact
anyone could, based on the wbs script that is in the Science_Roadmap repo
already.

**Comment by sethdigel** [comment]
> I will need to do a bit of SRM-scraping work to make this file - or in fact anyone could, based on the wbs script that is in the Science_Roadmap repo already.

I looked for a way to modify bin/gen_wbs_csv.csh to have it pull out Activities ('AC:...') rather than Deliverables ('D:...') but my understanding of shell scripts is not up to it.  Do you have any advice @drphilmarshall  ?

**Comment by drphilmarshall** [comment]
Looking at this now. @sethdigel You had mentioned ordering the deliverables/activities by their IDs as well as their titles: the csv file we currently write out contains the "ID" of the deliverable, which is its latex label. We could also use any mixture of the information in the file to compose an informative code. Here's a snippet from the file:
```
ID, Deliverable Title, Host, Era, Type, Start Date, Due Date, Status, Dependencies, KP ID, KP Name, KP Title, KP Host, KP Era
D:CI2-FW,"Software Framework Implementation",CI,DC2,SW,10/01/16,06/30/18,active,"",P:CI:SF,CI2,"The Initial Elements of a Software Framework",CI,DC2
D:CI2-DCDE,"Distributed Code Development Environment",CI,DC2,SW,10/01/16,02/28/18,done,"",P:CI:SF,CI2,"The Initial Elements of a Software Framework",CI,DC2
```
I'll make the script write out an activities file and think about the best code to use. My first thought is that I'd want to search by WG, DC era, deliverable name, in that order, so the ID plus the title is already pretty close to that _in most but not all cases_. I would be in favor of using this piece of pub system development to stimulate the homogenization of the labels/IDs in this way - but that won't happen soon. Are we prepared for the deliverable IDs and titles all changing?

**Comment by sethdigel** [comment]
Thanks, Phil.  Yes, you had stipulated that they could change, and change dramatically after periodic updates to the SRM.  The understanding that we have with Charlotte is that when this kind of change happens, she would be given a file that maps the old ID/names to the new ID/names, and she could update the database entries for existing Projects behind the scenes.

**Comment by drphilmarshall** [comment]
Good good. OK, PR is open at https://github.com/LSSTDESC/Science_Roadmap/pull/386, for your review, @sethdigel . Example activities file is here: [srm.activities.csv](https://drive.google.com/open?id=1pBBXTUfjgyehha-pkeIr7bRLzoKJ-6c8) - at least the ID and deliverable title columns (1 and 2) look in good shape.

**Comment by sethdigel** [comment]
Charlotte has implemented pick lists for SRM Activities and Deliverables on the page for defining Projects.  She is going to update the Project display page to show the selected Activities and Deliverables; the current version of the page (e.g., [here](http://portal.lsstdesc.org/Pubs/projectView.jsp?projid=3&swgid=4 in the Dev system) has placeholders to display the information.

**Comment by drphilmarshall** [comment]
Great stuff! We are getting very close now :-)

**Comment by sethdigel** [comment]
Charlotte has got the system displaying the selected deliverables.  Thank you, Charlotte!
