### ISSUE TITLE
pubs download not asking for login password before downloading doc

### ISSUE THREAD

**Issue by chee999** [LSSTDESC/desc-publications#102]
If you cut and paste a url to a document the pub system just serves the document without checking
if the user is logged on. Would like something like the CAS system to authenticate user.

**Comment by sethdigel** [comment]
Charlotte:  This seems to have been resolved, right?

**Comment by chee999** [comment]
The login bit is fixed but I still need to add the mimetype to the database.

**Comment by sethdigel** [comment]
> The login bit is fixed but I still need to add the mimetype to the database.

I think that this issue can be closed.  That is, I think that the mimetype is a separate issue (that you have resolved).  Right?

**Comment by sethdigel** [comment]
Charlotte has implemented this.
