### ISSUE TITLE
Reaching non-existent projects through URLs

### ISSUE THREAD

**Issue by sethdigel** [LSSTDESC/desc-publications#103]
If I try to look up a non-existent Project using a URL (such as might be constructed by the URL shortener), I get taken to a page for that Project anyway.  The page offers to let me add a document to the Project.  For example:
http://portal.lsstdesc.org/Pubs/projectView.jsp?projid=999

Ideally, the system would instead give a message like 'Project does not exist' and maybe provide a link to the top-level page of the Publication Management System.  Generating a server error message woul be fine too.

For reference, if I try to look up a non-existent paper, e.g., with
http://portal.lsstdesc.org/Pubs/download?paperid=999
I get '500 - Internal server error'.  That's fine.

**Comment by sethdigel** [comment]
Just for the record, I tried
http://portal.lsstdesc.org/Pubs/projectView.jsp?projid=xyz
just to see what would happen.  I got a '500 - Internal server error', which seemed appropriate.

**Comment by chee999** [comment]
This is fixed. The user gets a permission denied message indicating the project number entered doesn't exist.
