### ISSUE TITLE
DESC Members with Observer status

### ISSUE THREAD

**Issue by chee999** [LSSTDESC/desc-publications#106]
Should DESC members with Observer status (e.g. no data rights) be able to read/download documents?

**Comment by drphilmarshall** [comment]
Yes, please. ATM most observers are really "pre-members" who will benefit from access to this information. We may need to make this a real category at some point, but for now, Observers should be able to read docs but if possible not edit projects or publications. If that is not easy to do, they could have standard Member permissions.

**Comment by sethdigel** [comment]
Do we need to worry about Observers not having LSST data rights, in terms of access to the Pubs system?  I'd have thought so, although that is not an immediate issue.

Are the rights of Observers written down someplace?

**Comment by chee999** [comment]
An applicant with Observer status has one year to decide if they want to join. After that they are set to 'inactive'.   This was a conversation with the membership committee early on but I don't think it was written down, except in my notes.
