### ISSUE TITLE
Updates to / comments about projects

### ISSUE THREAD

**Issue by rmandelb** [LSSTDESC/desc-publications#11]
Here are my comments on the individual project pages:

- We need to define what is a Key Project.  There is a particular confusion that could easily arise: we have SRM key projects, and we have Pub Policy key projects, and they are not the same thing!

- I think we should have another status option: paper(s) under review.  I could imagine a use case where we wanted to identify projects that have paper(s) under review.

**Comment by chee999** [comment]
I've added Papers_under_review to the list of states for a project.

**Comment by chee999** [comment]
Projects no longer need to be marked as a 'key project', only papers need to have this as a possible status.
'paper_under_review' has been added as one of the possible states of a document.
