### ISSUE TITLE
Upload New Document menu item

### ISSUE THREAD

**Issue by sethdigel** [LSSTDESC/desc-publications#112]
This menu item should be renamed something like 'Upload new version of a document'.  

Also, the table it generates for the user to select from says "Choose your paper".  I'd recommend "Choose your document" instead.

And the table just lists the (short?) titles of the documents, and the list is likely to get very long.  Would it be possible to prefix the entries with the working group acronym (e.g., CL, TJP, WL, etc. or Mgmt)?

What determines which documents get listed in the table?  My impression is that it is just listing everything it knows about.  That is ok, but for example, I would not expect new versions of published papers to be uploaded, so those could be excluded from the list.

**Comment by chee999** [comment]
After reviewing how users may upload documents the 'Upload' option has been removed from the pull down menu. Members will need to navigate to the document to upload a new version.
