### ISSUE TITLE
JSP error on updating document metadata

### ISSUE THREAD

**Issue by sethdigel** [LSSTDESC/desc-publications#115]
For DESC-5, I just attempted to add a Confluence URL.  When I clicked on 'update' I got this error message:

Error=javax.servlet.jsp.JspException: update descpub_publication set modifydate=sysdate,modby=?,summary=?,can_request_authorship=?,title=?,builder_eligible=?,published_reference=?,ads=?,short_title=?,confluence_url=?,pubstate=?,inspire_number=?,arxiv=?,key_paper=?,passed_internal_review=?,paperid=?,doi=? where paperid = ? : Invalid column index
field=modifydate=sysdate value=digel
field=modby=? value=Paper describing DESCQA
field=summary=? value=N
field=can_request_authorship=? value=DESCQA: An Automated Validation Framework for Synthetic Sky Catalogs
field=title=? value=N
field=builder_eligible=? value=2018
field=published_reference=? value= ApJS
field=ads=? value= 234
field=short_title=? value= 36
field=confluence_url=? value=2018ApJS..234...36M
field=pubstate=? value=DESCQA
field=inspire_number=? value=https://confluence.slac.stanford.edu/pages/viewpage.action?pageId=221077703
field=arxiv=? value=Public
field=key_paper=? value=1627569
field=passed_internal_review=? value=1709.09665
field=paperid=? value=Standard
field=doi=? value=Y

I wondered if it might be complaining about the URL being https instead of http.  So I tried it the latter way - and got the same error message with that URL as well.

**Comment by chee999** [comment]
This should be fixed now.
