### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by rmandelb** [LSSTDESC/desc-publications#12]
Here are my comments on navigating the site:

- I wasn't clear on the purpose of what's currently in the top menu bar.  It seems to have a lot of semi-random things that are not particularly associated with publications/projects (e.g., links to WL telecon page).  But at the same time, it *doesn't* seem to have buttons that let you navigate around the publication site - e.g., go back to front page, project list, ...

- It feels too tricky to get to publications.  The only way I could find was by clicking on individual projects, and then I found a link to their papers.  Shouldn't we have a page that lists projects and another that lists publications, directly accessible from the top menu bar and front page?

**Comment by chee999** [comment]
These navigation links have been added.

**Comment by rmandelb** [comment]
@chee999 - I wanted to bring to your attention that the new navigation links show up in a strange location, at least on my browser.  You can see this screenshot:
![desc publications](https://user-images.githubusercontent.com/1454906/29852236-09439df2-8d07-11e7-9f04-133adc5c7b74.jpg)
At first I didn't see them, but then I realized they are quite small and way over to the right-hand side, whereas it's the top navigation bar over the DESC logo on the left side that catches the eye at first.

do you see what I mean?

I think the top navigation bar over the DESC logo on the left side should actually be replaced by the navigation links that are currently off to the side.
