### ISSUE TITLE
Remark field for document upload

### ISSUE THREAD

**Issue by sethdigel** [LSSTDESC/desc-publications#120]
From Pat Burchat:

_When I selected a file to upload to the DESC-22 note, an error was presented if I did not enter a “Remark”; see second attached screenshot._

I'd like to ask that entering text in the Remark field be made optional.

**Comment by chee999** [comment]
Remark field no longer required

**Comment by sethdigel** [comment]
> Remark field no longer required

Great!  Thank you, Charlotte.

@burchat
