### ISSUE TITLE
Comments on lead author assignment

### ISSUE THREAD

**Issue by sethdigel** [LSSTDESC/desc-publications#122]
From Pat Burchat:

_The lead authors appear in alphabetical order.  Is there a way to change that so that the “lead lead author” comes first?
[Interestingly, the Reviewers do not appear in alphabetical order…]
I added two reviewers (Douglas Clowe and Rachel Mandelbaum).  Are the paper authors supposed to be able to do that??_

Let's talk about these, Charlotte.  I suspect that there's no way to distinguish a 'lead lead' author in the system.  I don't feel strongly about it, since it does not relate to the ultimate order in the author list, but if it is easy to implement then I'd be in favor of doing so.

Formally, the conveners of the relevant WG name the internal reviewers for the papers in their WG.  So probably we'll avoid some confusion if we enforce that only conveners can add reviewers in the Pubs system.

**Comment by chee999** [comment]
The reviewers are now displayed in alphabetical order.

**Comment by sethdigel** [comment]
Thank you, Charlotte.  We confirmed that the system pays no attention to the order that the names of authors are clicked, so there's no way to designate a 'lead' lead author in Pubs.  (And in any case, the order of authors on resulting publications is determined separately.)  I am going to go ahead and close this issue.

@burchat
