### ISSUE TITLE
Allow for several SRM entries and SRM deliverables per project?

### ISSUE THREAD

**Issue by PierreAstier** [LSSTDESC/desc-publications#124]
I was not able to map several SRM activities and/or several SRM deliverable to a single project. I don't know if this makes sense, but the tree rings project that I just entered could justify this need. If the pub system is used to evaluate how Projects cover the SRM, allowing several SRM entries per project may be needed. Of course, I am assuming that updating the SRM frequently is not an option (!)

**Comment by sethdigel** [comment]
I was able to show Pierre how to select multiple activities and deliverables.  We have an issue already to add a note to the page (e.g., '(used command-click or ctrl-click to select multiple entries)').  So I will close this issue.
