### ISSUE TITLE
Publication page

### ISSUE THREAD

**Issue by rmandelb** [LSSTDESC/desc-publications#13]
On the publication page, it isn't clear what's meant to go in entries like "Telecon" or "Journal_Review".  Should have a few words explaining what those are for.

**Comment by abmantz** [comment]
I was expecting to see a list of authors here, eventually with roles and maybe even contribution statements.

It was also not clear to me that the options under "State" are a mutually exclusive set or a linear sequence. Some of them (the approvals) might be more appropriately check boxes.

Minor quibble: I don't think there's such a thing as an "Assigned PB Reader", although there will probably be a responsible PB representative for a given paper.

**Comment by chee999** [comment]
I used the despub model as a place to start for creating the DESC publication system so any of the items that are not relevant to DESC can be removed.
I've removed the field 'Telecon' and changed 'Assigned PB Reader' to 'Responsible PB Reader'.  
The list of authors on a publication is coming soon.

**Comment by sethdigel** [comment]
Yes, 'Assigned PB Reader' was based on what the DES system shows.  Rather than just getting rid of it I asked Charlotte to change it to 'Responsible PB Reader'.  I am imagining that we'll want at least one member of the Pub Board to read each paper that is up for approval to submit.  I haven't figured out how that person would register approval in this system, however.

**Comment by chee999** [comment]
Regarding Adam's question about "State", currently a publication is only in one state at a time and I'm assuming (probably incorrectly) that the person(s) responsible for shepherding the paper through the approval process would select the state of the paper. If a publication can be in more than one state at a time what are those states?

**Comment by abmantz** [comment]
It seems like the available states have changed since my original comment, so it may no longer be relevant. In any case, I can't remember what the options were at that point.

**Comment by chee999** [comment]
These issues have been resolved in the latest test version.
