### ISSUE TITLE
Need ability to upload and download publications and documents

### ISSUE THREAD

**Issue by chee999** [LSSTDESC/desc-publications#15]
The DESC publication system will need a way to upload and download publications and documents plus disk space to store large files (NFS space preferred).  Directory hierarchy will also need to be worked out so that versions of each publication or paper are available.

**Comment by tony-johnson** [comment]
In the past we have used Apache Commons FileUpload for this. It is included by default by org-srs-web-base which we are using (possibly a slightly out-of-date version). The web site is here:

https://commons.apache.org/proper/commons-fileupload/

This has built-in support for streaming uploads directly to disk (see https://commons.apache.org/proper/commons-fileupload/using.html).

**Comment by chee999** [comment]
Upload and download of papers has been added to the latest test version.

**Comment by chee999** [comment]
Upload/download now part of production version
