### ISSUE TITLE
Publications and Mailing Lists?

### ISSUE THREAD

**Issue by chee999** [LSSTDESC/desc-publications#16]
For each paper/publication a group will be created to control access to the paper.  Publication administrators would be able to add/remove members from such a group.
Do we need a mailing list for each or some of the papers/publications?  If you want to send a message to everyone involved on a paper but not necessarily an author how would you do that?

**Comment by sethdigel** [comment]
Good question. The papers formally will not have authors (other than the primary authors) until the signup period just before the paper is submitted.  So we need the equivalent of mailing lists just for projects.  Maybe the project leads should be required to define the name of the e-mail list corresponding to the project (?).

**Comment by chee999** [comment]
Every document that belongs to a project should have 3 groups associated with it:
paper_nnn
paper_leads_nnn
paper_reviewers_nnn
The primary authors can add/remove authors by adding or removing members from the paper_nnn group.
Same for the reviewers group. 
For papers that do not have a project how are members assigned to it?

The primary authors would need to make a request for a mailing list.

**Comment by sethdigel** [comment]
I think that this issue can be closed.

**Comment by chee999** [comment]
Issue resolved
