### ISSUE TITLE
File uploading catch-22?

### ISSUE THREAD

**Issue by sethdigel** [LSSTDESC/desc-publications#17]
My understanding is that uploaded documents will be assigned a document number when they are uploaded.  Is there a way that the (pending) document number can be shown before the file is uploaded?  This would allow, say, the document number to be included within the document itself, e.g., for DESC notes.  I wouldn't say that this is an absolute requirement, but I think we'd find it useful.  (An alternative would be to upload a DESC Note, find out what the document number is, then upload a new version of the Note with the document number included.  I'm assuming that versioning would be supported.)

**Comment by chee999** [comment]
Hi Seth,

The current way of assigning numbers is to look at the last document or 
note that was successfully uploaded and take its number and increment 
it by 1.

On the upload page this number could be displayed as the 'pending'
number. If the upload fails nothing is assigned. If successful,
the uploaded document or note gets the incremented number.
Is this what you mean?

regards, Chee

**Comment by sethdigel** [comment]
Yes, that is what I had in mind.  I don't think it would be bullet-proof because someone else could upload something in the meantime, but I think that would not happen very often, and if it did, the fact that you end up with a different document number than you expected would not be a big problem.

**Comment by chee999** [comment]
Hi Seth,

Tony reminded me that you have to create the document or paper entry first 
so the number is assigned at that time. Then you select the document or 
paper from a list of files to upload. That should solve chances of 
colliding with someone else.

regards, Chee

**Comment by sethdigel** [comment]
Great!

**Comment by chee999** [comment]
Currently the publication is 'paper'_N  where N is the paperid (e.g. 
paper_1, paper_2, etc).  This may be too plain?

**Comment by dkirkby** [comment]
I recommend a single counter for all pubs, e.g., DESC-PUB-nnnn, rather than using separate counters for each subgroup, since this is simpler and decouples the naming scheme from any assumptions about the subgroup hierarchy.  (FWIW, this is the approach adopted by DOCDB and the BABAR pub system).

**Comment by sethdigel** [comment]
Ok, good point.  How about DESC-DOC-nnnn or DESC-nnnn?  To me 'PUB' implies publication.  I could get used to it. Most of what gets uploaded will not be journal publications, although I suppose they could be 'publications' in the broad sense described in the DESC Pub Policy

**Comment by sethdigel** [comment]
@chee999 We'd like to go with "DESC-n" (i.e., without zero filling) as Phil describes above, for everything uploaded to the system.  

For downloads, ideally the file created would include the version number in the name.  E.g., if DESC-123 is a PDF file and the user requests the third version, then the file would be named DESC-123v3.pdf.

**Comment by tony-johnson** [comment]
In the spirit of breaking down barriers we should be able to go to http://ls.st/DESC-123 and be redirected to the right place. I am not sure who we have to coordinate with to make that happen but I can find out.

**Comment by sethdigel** [comment]
This [policy](https://dev.lsstcorp.org/trac/wiki/DM/Policy/ls.st) statement looks a bit old, but at least at the time, the URL shortener was said to be only for Project-related resources.

**Comment by chee999** [comment]
I noticed that the DES Fermilab style is to include the year, e.g. DESC-2017-1, DESC-2017-2, etc. Do we want to include the year in the name?

**Comment by sethdigel** [comment]
Thanks for asking, Charlotte.  We'd like to stick with DESC-1, DESC-2, etc. naming.

**Comment by chee999** [comment]
I think this problem has been solved.
