### ISSUE TITLE
Non-project related file uploads

### ISSUE THREAD

**Issue by sethdigel** [LSSTDESC/desc-publications#18]
Richard has asked whether the publication management system can be a place where general DESC-related documents are stashed and made findable.  I think that what he has in mind might be DESC notes-type files that belong to (say) a technical working group but are not necessarily in a particular defined project in that group, but will useful within DESC.  Other possibilities might be DESC collaboration governance documents.  Or overview presentations about LSST.  I had not been thinking that the publication management system might be used in this way.

I can vaguely imagine that this could work, though.  At least I'd imagine that a page could be provided to upload documents that have no designated project and might or might not have a designated working group(s).  The person uploading the file would provide a title and select a category (like DESC Note, presentation, etc.).  Then a corresponding download page would allow the user to sub-select by category.  What I'm less clear about in terms of feasibility is whether anyone in DESC could upload anything (probably) and whether anyone could upload a new version of something.

**Comment by chee999** [comment]
Is this still a desired feature? It is possible to skip the project creation step and go straight to the create document step. I would prefer these documents have an extra "tag" indicating they are "project-less" but
that can be added behind the scenes. Who would be allowed to edit? Document leads or anyone who is a full-member?

**Comment by sethdigel** [comment]
Yes,  this is still a desired feature.  The idea would be that the documents would be Project-less as you note but still would be associated with a given WG.  

So the page for a WG (e.g., httpportal.lsstdesc.org/Pubs/show_swg.jsp?swgid=4) could have a 'WG Documents' table below the Projects table, and a button for adding a WG document.  Alternatively, the first entry of the table that lists the WG Projects could be an entry for the WG documents, with a link to a page that lists the documents and with an 'Add document 'link.

**Comment by chee999** [comment]
Is it true that only document types that are **not** one of these can be project-less?
Journal paper
Data release
Proceedings paper
Seminar material
Conference contribution
Astronomical circular
Thesis
Software_tool
Note
Working Group presentation
Policy
External Collaborator Proposal

**Comment by sethdigel** [comment]
That sort of looks like a 'gotcha' because you have listed every document type in the system.  The types that would be possible for a document belonging to a WG but not to any particular project would be 'Note' and 'Working Group presentation'.  If it is trouble to customize the list for this case, I would recommend just keeping the full list.

**Comment by sethdigel** [comment]
For what it is worth, I tried creating and uploading a project-less file for the Dev Clusters working group.  I got past the part where you enter the title, etc., but then got a Server Error when I tried to upload a PDF file to it.  Here's a screen shot just before I clicked Upload Document.
<img width="517" alt="projectless-upload" src="https://user-images.githubusercontent.com/6035835/43868641-68950482-9b23-11e8-8d30-a56880f3c10f.png">
Probably for the better,  file-less and Project-less document does not appear on the main page for the Clusters working group.

**Comment by sethdigel** [comment]
(Documenting a discussion with Charlotte)  We confirmed that the system accepts uploads of Project-less documents, but it isn't clear where they go.

**Comment by chee999** [comment]
Project-less documents are now being tracked. A project-less document is associated with a working group. Where should this information be displayed?

**Comment by chee999** [comment]
fixed or added requested features.
