### ISSUE TITLE
Comments on the roles of the top-level pages

### ISSUE THREAD

**Issue by sethdigel** [LSSTDESC/desc-publications#21]
The highest-level page http://portal.lsstdesc.org/Pubs/  currently has a table with three columns (Working Groups, Working Group Convenors, and Update Working Group Members).  Only the first column is really needed here.  The Conveners for a given working group can be listed on the top-level page for that working group (along with the links to their entries in the User and Group Manager that you already include).  

The page http://portal.lsstdesc.org/Pubs/ ideally would also have a list of the most-recent 'active' publications, with links to their corresponding pages.  We don't have a complete idea about what 'active' should mean - maybe recently uploaded files or a change in state (like created, in review, etc.). This top-level page ultimately would include links to various kinds of summary reports (that we can define later)

The top-level page for a working group is where people should have the option to affiliate themselves with the working group (which I guess is equivalent to subscribing to the mailing list for the WG).  The top-level page for a working group should also have a link to list the various members of the working group.  And it could have a link for administering membership of the group, but ideally the option would appear only for people with the right level of access (like convenors of the WG).

The page for a Project should allow anyone participating in that project to upload a document (say an analysis note) related to that project.  And it should provide a listing of documents that have been uploaded to it, along with a (separate) listing of papers that belong to the project.  This listing can link to the Discourse forum for that paper, once we get that far.

Similarly, the page for a journal paper in preparation should allow the lead authors to upload drafts, and to see a table with previous versions.  This page should also provide a link to the Discourse forum (or whatever we use) to manage the feedback from reviewers and from the collaboration at large.

**Comment by sethdigel** [comment]
Also, ideally the top-level page for the Publication management system would include a search box (#20).

**Comment by chee999** [comment]
On Fri, 27 Oct 2017, Seth Digel wrote:

> Date: Fri, 27 Oct 2017 21:21:00 +0000 (UTC)
> From: Seth Digel <notifications@github.com>
> Reply-To: LSSTDESC/desc-publications
>     <reply+007691b1bc68b88e1559093a0f32a684b3bcce5d1644798292cf00000001160b653
>     c92a169ce100c41a7@reply.github.com>
> To: LSSTDESC/desc-publications <desc-publications@noreply.github.com>
> Cc: Subscribed <subscribed@noreply.github.com>
> Subject: [LSSTDESC/desc-publications] Comments on the roles of the top-level
>     pages (#21)
> 
> The highest-level page http://portal.lsstdesc.org/Pubs/  currently has a table with three columns (Working Groups, Working Group Convenors, and Update Working Group Members).  Only the first column is really needed here.  The Conveners for a given working group can be listed on the top-level page for that working group (along with the links to their entries in the User and Group Manager that you already include).
>
> The page http://portal.lsstdesc.org/Pubs/ ideally would also have a list of the most-recent 'active' publications, with links to their corresponding pages.  We don't have a complete idea about what 'active' should mean - maybe recently uploaded files or a change in state (like created, in review, etc.). This top-level page ultimately would include links to various kinds of summary reports (that we can define later)

There is a link in the top tool bar that takes you to the publications 
page which has a link to each paper.

>
> The top-level page for a working group is where people should have the option to affiliate themselves with the working group (which I guess is equivalent to subscribing to the mailing list for the WG).  The top-level page for a working group should also have a link to list the various members of the working group.  And it could have a link for administering membership of the group, but ideally the option would appear only for people with the right level of access (like convenors of the WG).
>
Users would go through the GroupManager to sign up.


> The page for a Project should allow anyone participating in that project to upload a document (say an analysis note) related to that project.  And it should provide a listing of documents that have been uploaded to it, along with a (separate) listing of papers that belong to the project.  This listing can link to the Discourse forum for that paper, once we get that far.
>

The functionality of uploading a paper is working but the folder hierarchy 
which depends on the format of the paper naming convention has to be 
clearly defined before adding the upload feature to the project section.

> Similarly, the page for a journal paper in preparation should allow the lead authors to upload drafts, and to see a table with previous versions.  This page should also provide a link to the Discourse forum (or whatever we use) to manage the feedback from reviewers and from the collaboration at large.
>

Same answer as above.

regards, Chee

**Comment by sethdigel** [comment]
Thank you, Charlotte.  The discussion in #17 converged on a 'flat' naming scheme for uploaded files, 'DESC-n', where n stands for the document number assigned by the system, with no zero filling.  We'd also like to have version numbers included.  So an example file name could be DESC-123v3.pdf

**Comment by chee999** [comment]
These issues have been resolved.
