### ISSUE TITLE
Sending e-mail from pubs application

### ISSUE THREAD

**Issue by tony-johnson** [LSSTDESC/desc-publications#23]
There are several cases where we need to send e-mail from the pubs application (e.g. when a user requests author access). In the past we used the apache mailer taglib, but this is unsupported, and does not easily produce good looking e-mails.
I suggest we use a different system, where e-mails to be sent are pt into a few database tables, then a simple timed tasks pulls e-mail from those tables and sends it. The tables could look like:

LSSTDESC_PUBS_MAILBODY: ID,  Subject, Body
LSSTDESC_PUBS_RECIPIENT; ID, Name, Address

All e-mails would be sent with a from address of "LSST DESC Pubs system" <noreply@lsstdesc.org> and a reply-to address of chee@slac.stanford.edu

**Comment by chee999** [comment]
The reply-to-address would need to be either lead authors, project leads or admins.

**Comment by chee999** [comment]
Will email to Discourse be an option?

**Comment by chee999** [comment]
Changed the mail routine to use an Oracle sequence instead of looking at the last msgid and incrementing it by one.

**Comment by sethdigel** [comment]
I think that this can be closed.  Also, Discourse is out of the picture.

**Comment by sethdigel** [comment]
This issue has been close-able for some time.
