### ISSUE TITLE
Main DESC pub page (1.2)

### ISSUE THREAD

**Issue by sethdigel** [LSSTDESC/desc-publications#24]
In version 1.2, the [main page](http://portal.lsstdesc.org/Pubs/) has a column headed 'Update Working Group Members (Admins Only).

The links are apparently to pages where a user with Admin privileges can change the conveners of the selected group.  This is not something that happens very often - on the order of annually - and I'd recommend that it not be functionality in the Publication management system.  I guess you must already have a non-Pub management system way to do this, and I think that is enough.

If possible, I'd make the heading something like 'Join the working group' and have a links to the page where individuals can sign themselves up for a given working group.  Or the column could be omitted.

**Comment by chee999** [comment]
The  working groups column has been removed.

**Comment by sethdigel** [comment]
Charlotte has resolved this issue
