### ISSUE TITLE
Comments on the project pages (1.2)

### ISSUE THREAD

**Issue by sethdigel** [LSSTDESC/desc-publications#25]
Here are some comments and questions on the page for a given project, e.g., [this one](http://portal.lsstdesc.org/Pubs/show_project.jsp?projid=86&swgid=4).

How are the Project IDs assigned?  I am not sure that we need to see the Project ID numbers, but maybe I have not thought it through enough.  We'll certainly refer to documents by number (internally) but I think that we will refer to Projects only by their names.

Also, we do not need the 'Key Project' field.  I was reminded that 'Key Project' is a term in the Science Roadmap document but this does not translate to something we need to track in the Publication Management system.  (We do still need to have the ability to flag individual papers as Key Papers.)

In the 'State' field I'd suggest removing 'Paper_Under_Review'.  Projects can have more than one paper.  Also, I think that 'Active' covers the circumstance.  I'd recommend listing the remaining entries in more or less chronological order:  Created, Active, Completed, Inactive.

In the table under 'List of Document Entries', is there any way to list the type of document (e.g., paper draft, DESC note, etc.?)  I guess that this could be based on the Pubtype field defined when a document is uploaded.

**Comment by chee999** [comment]
Here are the replies to the comments/questions above:
Project IDs:
Project ids are assigned through an Oracle sequence and the id is used to create the associated groups in the GroupManager that control what privileges (read,write,update) a user has for the specified project. Each project has two GroupManager groups and the names are the word 'project' concatenated with the project id
e.g. project_1 (members of project 1) and project_leads_1 (members who can create and modify a project add or remove project members and are the main contact for the project).

Key Project:
The key project field has been deleted. Key paper field is retained on documents.
 
State:
The state field has been updated to have only 'created', 'active', 'completed', 'inactive' (in that order).
 
Type of document:
pubtype has been added to 'List of Document Entries' table
