### ISSUE TITLE
Documents associated with Projects (1.2)

### ISSUE THREAD

**Issue by sethdigel** [LSSTDESC/desc-publications#27]
On the page for a Project (e.g., [this one](http://portal.lsstdesc.org/Pubs/show_project.jsp?projid=86&swgid=4) can a table be included with a list of internal documents (presentations, DESC Notes, etc.) that are associated with the project?  

Can a link be provided on the page for a given Project to upload such internal documents for that Project?  An internal document would have similar metadata to be recorded but would not have any bibliographic information or links to internal review.

**Comment by chee999** [comment]
Here are the replies to the above comments.
Project page:
Table of documents associated with project exists. The type of document is also shown.

Upload document:
Documents may not be uploaded until an entry has been made for the document. The link to upload the document appears on the publication page of that document.
