### ISSUE TITLE
Define requirements for publications permissions system

### ISSUE THREAD

**Issue by tony-johnson** [LSSTDESC/desc-publications#3]
Currently there are no permissions in the publications system. We need to define a list of actions (e.g. create project, add publication, request to join author list, ...) and for each action which group or role a user needs to be able to perform and action, who should be notified, and if approval is required.

**Comment by chee999** [comment]
Administrator Access | Working Group | Projects | Documents
-------| --------------| -------- | ---------
GroupManager Admins | x | x | x
Publication Admins  | x | x | x
Project Leads       |   | x | x   
Lead Authors        |       |  | x

**Comment by sethdigel** [comment]
Here's a table that Charlotte posted on this issue yesterday (according to an e-mail that I got from GitHub).  Wherever the table is, I can't find it, and I'd like to add a comment, so I am posting it here.

Administrator Access | Working Group | Projects | Documents
-- | -- | -- | --
GroupManager Admins | x | x | x
Publication Admins | x | x | x
Project Leads |   | x | x
Lead Authors |   |   | x

I think that this table is not quite complete:  
Working Group conveners can create Projects (and designate leads for the projects) within their working groups.  

Also, DESC members need to be able to add themselves to Projects (not as leads but as participants or 'members').  

Project leads can create entries for journal papers within their projects (and designate lead authors).

Within Projects, DESC members need to be able to upload documents (analysis notes, etc.).
