### ISSUE TITLE
Additional 'working groups'

### ISSUE THREAD

**Issue by sethdigel** [LSSTDESC/desc-publications#32]
With the DESC-Pub serving as a repository for all DESC-related documents, the Pub Board is recognizing that we'll want to upload documents that don't belong to any of the analysis or technical working groups.  The prime examples are policy documents, or documents related to data challenges that in effect relate to all of the working groups.

I'd like to ask if you could make two additional working groups in the DESC-Pub system:  Leadership and Management.  They would map to the current Leadership and Management group membership.  

These working groups would not have projects, etc., but we'd need to be able to upload (and find) documents with these working group assignments.

**Comment by rmandelb** [comment]
Would they really not have projects?  I would think of the SRD work as a project, with two documents: the actual SRD and its associated tech note.

**Comment by sethdigel** [comment]
Especially if you think it would be useful, then I suppose we could use a model that had projects associated with the Leadership and Management groups.  I was thinking more about DESC policy documents - but I suppose that for development (or maintenance) of policies, they could be organized into projects as well.

How about also making a Collaboration Council 'working group'?  It might make more sense to have the CC 'own' the policy documents.

**Comment by rmandelb** [comment]
I think it depends which kind of policy documents.  Certainly things like membership policy and publication policy should (IMO) be owned by the CC, but were we going to be putting those documents in the publication system?  That wasn't obvious to me.

There is room for some policy documents owned by management.  For example, the spokesperson (not CC) is the one who signs MOUs with other organizations, so if we consider those as policy documents then management is their owner.

But again I think there's also a question of whether we're going to use this system for those things.  Are we?  I had originally raised the question of mgmt/leadership ownership of documents in the context of the SRD, which has some scientific content in addition to being used to help prioritize operations funding (while not being a policy document itself).  I'm less sure that purely policy documents need to go in here.  The benefit I can see of doing that is that we have all documents in one place; the disadvantage is that I don't see them as needing the same kinds of things (reviews etc.) and the "owners" need different levels of control.

**Comment by sethdigel** [comment]
I think that the motivation for keeping policy-type documents in the system is that they will be assigned DESC document numbers, and the system will keep track of versions.  We may also be able to engineer a way to make them publicly accessible without having to copy them to http://lsst-desc.org.  Yes, the publication management system would need to have a 'policy' document type (or something like that) and for these, it would not try to ask for bibliographic information, internal reviewers, etc.  (This is also the case for other non-journal paper 'documents' that the system will track, like internal notes and presentations.)

**Comment by chee999** [comment]
The two working groups 'management' and 'leadership' have been added.
