### ISSUE TITLE
Rearrange show_pub.jsp layout to be more user-friendly

### ISSUE THREAD

**Issue by chee999** [LSSTDESC/desc-publications#38]
On the show_pub.jsp page only display the information along with an 'edit' option. The display will look cleaner and easier to read. If the person really wants to edit they must click the 'edit' button. This is similar to the Group Manager for a person's profile. As in the Group Manager, the 'edit' button should only appear to those users who have permission to make changes.
Move the 'upload' section to this page instead of having to go to another page to upload.

**Comment by sethdigel** [comment]
Please also include the table of uploaded drafts directly on this page, near the top (like just below the Brief Summary).  Also, if possible, please make the default width of the Brief Summary box wider so it takes up less vertical space on the page.  I'd suggest 2x wider.

**Comment by chee999** [comment]
Users with edit privileges must click 'edit' to make changes. The 'upload' section has been included in this page and the summary is wider, reducing the space it takes up vertically.
