### ISSUE TITLE
Rearrange show_project.jsp for greater user-friendliness

### ISSUE THREAD

**Issue by sethdigel** [LSSTDESC/desc-publications#39]
* Please move the Brief Summary box up to just below the Title box, and make the Brief Summary box wider.  

* Please also move the list of documents to be just below the Brief Summary box.  

* I'd vote for making the document list be in reverse chronological order by default.  

* And I'd recommend splitting the list into two tables, with Note, Seminar material, Working group presentation, Data release, and Software tool (changed from Software_tool) in the second table.

**Comment by chee999** [comment]
The project page has been totally reworked so this no longer applies.
