### ISSUE TITLE
Re-enable discourse discussion system for evaluation as paper discussion system

### ISSUE THREAD

**Issue by tony-johnson** [LSSTDESC/desc-publications#4]

**Comment by sethdigel** [comment]
Can we add this to the release 1.0 milestone?

**Comment by sethdigel** [comment]
I'd propose closing this issue.  We will use Confluence for paper discussion (internal reviewer reports,   responses,  other discussion,  journal referee reports, responses to referees)

**Comment by chee999** [comment]
Confluence will be tried first. If Discourse comes up again a new issue can be filed.
