### ISSUE TITLE
Home / landing page should show a table of some publications, plus some options

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/desc-publications#49]
Right after I login (with my standard member permissions) it'd be nice to see some display of publications - the 10 most recently modified, perhaps, to help authors who are making a lot of changes to their paper's entry in the system? And then it'd be nice to have some buttons or links to various other options (eg "Start a New Project", "Start a New Paper" etc, plus a search box). What do you think, @chee999 ? Probably some bits of this are easier than others...

**Comment by sethdigel** [comment]
On the main page, the system does show you a list of the most recently uploaded documents, across the system.  (The heading is 'Most recent Documents'.  Maybe it could be 'Most Recently Modified Documents'.)

Also, standard Member accounts should not be able to create projects in the system.  Conveners can do this, and assign full rights within a project (e.g., to define papers) to specific people (who can then add other people).

**Comment by chee999** [comment]
Change the selection of the "most recent" based on the latest 10 instead of by time.

**Comment by chee999** [comment]
This is an old issue and the points have been addressed, I think.
