### ISSUE TITLE
Permissions to create Projects

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/desc-publications#51]
@sethdigel Who should be able to create Projects? I just managed it, and I believe I have only regular member permissions. Is starting a Project something any (Full) Member should be able to do? This is a pub policy question, I think.

**Comment by abmantz** [comment]
From @sethdigel in a different thread
```
Also, standard Member accounts should not be able to create projects in the system.
Conveners can do this, and assign full rights within a project (e.g., to define papers)
to specific people (who can then add other people).
```

**Comment by sethdigel** [comment]
@chee999, I think that this can be closed, right?  (That is, I think that you have got permissions implemented in the system.  And that Pub Board members may still have superuser-type privileges.)

**Comment by chee999** [comment]
reopen if this is still a problem
