### ISSUE TITLE
Projects page should list only the two WG conveners as WG conveners

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/desc-publications#52]
Right now [my SLRealizer Project page](http://portal.lsstdesc.org/Pubs/show_swg.jsp?swgid=5) lists Danny, Tom and Charlotte as my WG conveners. Only Danny and Tom are actually my WG conveners - so either @chee999 has temporarily given herself WG permissions to the SL group, or there's a bug.

**Comment by drphilmarshall** [comment]
Oops sorry - that's the [SL WG page](http://portal.lsstdesc.org/Pubs/show_swg.jsp?swgid=5) I just linked to, not my Project page! Still, same problem.

**Comment by rmandelb** [comment]
When I played around with my admin superpowers last week I saw that Charlotte was indeed listed as convener for a few WGs (presumably so she could play around with their views and make sure things were working).  It's a temporary feature, not a bug.

**Comment by drphilmarshall** [comment]
Super - closing out.
