### ISSUE TITLE
Project page needs some navigation aids and a null table of documents

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/desc-publications#53]
Suggestions for navigation aids on the (edit) Project pages:

* Can we make the project title appear bigger? It looks a little lost there.

*  After I have updated the details on my new Project page, I want to go back to the Projects page, but there's no hyperlink - it took me a while to realize that the navigation bar was way up at the top of the page.

* Projects that have documents have nice tables at the bottom of their pages - but new Projects don't have this. Maybe a note that says "No documents to display yet." would be helpful?

**Comment by drphilmarshall** [comment]
I was going to attempt a pull request to at least get each project's title and URL displayed on its `show_project.jsp` page - but I could not find the source code to edit. Here's a failing search:

https://github.com/LSSTDESC/desc-publications/search?utf8=%E2%9C%93&q=show_project&type=

Also it looks as though none of the code has been touched for 8 months, which suggests that the repo hosted at github.com is lagging behind the dev version.  @chee999, would you mind pushing your commits so we can see the current version please? Thanks!

**Comment by chee999** [comment]
Hi Phil,

Unfortunately, my github skills are still evolving so the current branch I'm working on has the terribly long name of 'FileUploadDownloadImprovements'.  That should contain the latest changes.

**Comment by chee999** [comment]
I've checked in the latest version of the code and I believe I merged it with master(?). I've also changed the project layout. If a project has no documents no table is shown but I can add a message saying no documents yet.

**Comment by drphilmarshall** [comment]
Thanks Charlotte! Good to be able to see the code. I submitted a PR, https://github.com/LSSTDESC/desc-publications/pull/75, in response to this issue, see what you think :-)

**Comment by sethdigel** [comment]
I see that Phil's pull request was merged.  Can this issue be closed @drphilmarshall ?

**Comment by sethdigel** [comment]
Closing this.  Phil's pull request was merged.
