### ISSUE TITLE
Project owner permissions: editing projects, not starting Notes

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/desc-publications#54]
Two things for pub board discussion:

1. As a regular member I can go to any Project page and edit its details, as if it was a wiki page. I guess that's cool, I was just a bit surprised.

2. Even as Project owner (initiator?), I don't seem to have permission to start a Note document in this project. I guess only WG conveners can do that, can they? Is this the right behavior? I guess its fine - it means that from my point of view, all the action will be on confluence, and someone else will do all the publication management. Maybe a lot of work for the WG conveners?

**Comment by drphilmarshall** [comment]
Regarding point 1, I notice that I can upload a new version of any publication in the system, regardless who owns it. See [this publication page](http://portal.lsstdesc.org/Pubs/show_pub.jsp?paperid=147) for an example.

**Comment by abmantz** [comment]
1. I think it's a bug for anyone to make changes to the Project page - that should be restricted.
2. Anyone who is signed on to a project should be able to initiate a note. We don't want the conveners to be overloaded.

**Comment by sethdigel** [comment]
I basically agree with 1., as long as 'restricted' does not mean restricted to 0.  Somebody needs the authority and the access to make tweaks.

I absolutely agree with 2.  I haven't thought about who, if anyone, should be able to delete a Note.  I don't expect it to come up very often.  

Issue #3 has a table and some notes about what I think we understand the various kind of permissions should be.

**Comment by sethdigel** [comment]
@chee999 and @drphilmarshall Can this issue be closed?

**Comment by sethdigel** [comment]
@chee999 and @drphilmarshall Can this issue be closed?  I think that Charlotte has gotten permissions implemented to address this issue.

**Comment by sethdigel** [comment]
Closing this - just confirmed that Charlotte implemented the permissions consistent with this issue.
