### ISSUE TITLE
Publications and Projects pages need nice big headings

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/desc-publications#55]
eg the [Publications page](http://portal.lsstdesc.org/Pubs/all_publications.jsp) just shows a big table of documents, but doesn't tell the user what they are looking at. Suggest a heading such as "LSST DESC Publications". I think this is (arguably) a documentation bug.

**Comment by chee999** [comment]
Added headings to projects and publications page. Added textbox for workspace url

**Comment by drphilmarshall** [comment]
Thank you! :-)
