### ISSUE TITLE
Publication pages need nice, accurate headings

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/desc-publications#56]
eg [this thesis](http://portal.lsstdesc.org/Pubs/show_pub.jsp?paperid=142) should say "Publication DESC-142" or "Document DESC-142", but not "Paper DESC-142" because theses are not papers. Then, I think it'd be nice to display the current value of the title as a heading for this page, so the user knows what they are looking at. Maybe put this header underneath the pub/doc number, but in bigger font?

**Comment by chee999** [comment]
The heading has been changed to use 'Document' instead of 'Paper'. The details appear in table format under the heading.

**Comment by chee999** [comment]
These changes won't appear until the next release.

**Comment by drphilmarshall** [comment]
Thanks Charlotte!

**Comment by chee999** [comment]
Release made
