### ISSUE TITLE
Should users be allowed to request authorship of theses? 

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/desc-publications#57]
I think not. Is it easy to throw an error message and return the user to their previous view? Of course such authorship requests will be rare, and easily ignored manually, but still - I thought this was (just about) issue-able.

**Comment by chee999** [comment]
Is thesis the only document that does not allow a request for authorship?
What about these two:
Software Tools
External Collaborator Proposal

**Comment by sethdigel** [comment]
Good question.  I think that the answer is no for both.  It would be nice to track the authors of software tools, but I think that will be clear in the released code itself and the Pub Management System will of course track the authorship of related publications.

**Comment by chee999** [comment]
Users are no longer allowed to request authorship for documents of type thesis, software_tool or external collaborator proposal.
