### ISSUE TITLE
Project pages need hyperlinks to their workspaces

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/desc-publications#59]
I think "Workspace" should be a property of a project: I want to enter a URL (probably confluence, but could be GitHub), and I'd like to see that link displayed on the Project's page in the pub mgmt system, under the title heading (#55) or something. It's really important to help people find project workspaces! I think if the project in the pub mgmt system is not hyperlinked to its workspace, that's a bug.

**Comment by chee999** [comment]
When a new project is created would the project workspace url be required, even as a placeholder if no workspace yet existed?

**Comment by drphilmarshall** [comment]
Yes, please: it's important that the collaboration be able to find out more
about projects, so if no URL is provided (and/or no project workspace
exists), it's a problem. I'd say a URL should be required. Thanks!

**Comment by chee999** [comment]
I've updated Pubs to require a workspace url

**Comment by drphilmarshall** [comment]
Great! I successfully added the URL to the SLRealizer project, [here](http://portal.lsstdesc.org/Pubs/show_project.jsp?projid=161). Thank you!
