### ISSUE TITLE
Shortcut URLs for DESC Documents

### ISSUE THREAD

**Issue by sethdigel** [LSSTDESC/desc-publications#61]
Is there any chance of implementing something like the Project's interface to DocuShare that would let you retrieve a particular document by constructing a URL with the document number in it, like http://ls.st/LCA-10147 for the most-recent version of the document and http://ls.st/LCA-10147* to be taken to the page that has the version history of the document?

**Comment by sethdigel** [comment]
This would be a popular and immediately useful feature.  Is it do-able?

**Comment by sethdigel** [comment]
Currently, links to documents in the system look like this  (for DESC-135)
http://portal.lsstdesc.org/Pubs/download?paperid=135&version=2

For a URL shortener to work, I think that we want a URL like this to work as well, and to point to the most-recent version of the document:
http://portal.lsstdesc.org/Pubs/download?paperid=135

This way, something like http://ls.st/DESC-135 could be redirected to the actual URL for the current version.

**Comment by sethdigel** [comment]
@drphilmarshall learned today from Iain Goodenow that the LSST people can configure their http://ls.st/ URL shortener to support our linking to DESC documents.  For this to work we will need to make the URLs not require the version number, as noted above.

**Comment by chee999** [comment]
So instead of a version number assume it is always the most recent version.

**Comment by sethdigel** [comment]
> So instead of a version number assume it is always the most recent version.

Yes, in the sense that if a version number is not specified the code should assume that the most-recent version is the one that's wanted.

**Comment by chee999** [comment]
@tony-johnson Do you know how we can automate, register, create  short urls  using ls.lst?

**Comment by sethdigel** [comment]
All that I am asking is for a URL like http://portal.lsstdesc.org/Pubs/download?paperid=135 to return the most-recent version of the paper.  There's nothing else that needs to be done on our side.

**Comment by sethdigel** [comment]
If you need to keep a '&version=#' part for Pubs/download, perhaps an alternative could be something like this: http://portal.lsstdesc.org/Pubs/download?paperid=135&version=0
where 'version=0' would be understood to refer to the most-recently uploaded version of the paper.

Either way, the idea is to have way for the URL shortener (wherever and whatever it is) to translate a request for 'DESC-135' into a URL that actually works to retrieve the most-recent version of the document.  Right now, that is not possible because the script (or whatever Pubs/downloads is) requires a version number.

**Comment by sethdigel** [comment]
Thanks for making this work!
