### ISSUE TITLE
Development version of Publication system for testing

### ISSUE THREAD

**Issue by chee999** [LSSTDESC/desc-publications#65]
Set up the development version of the publication system with only the working groups defined. Any projects or documents will be added by the pub board members. All data entered will be added to the configdev tables and can be deleted at any time.

**Comment by sethdigel** [comment]
Thanks a lot, Charlotte.  I think that the sense of 'Prod' and 'Dev' may be swapped, in the sense that I'd have expected Prod to have the 'clean' database tables.

**Comment by chee999** [comment]
Move the data currently in prod to dev tables. Figure out the sequence numbers for dev.

**Comment by chee999** [comment]
The data from Prod has been moved to Dev and the Prod tables are now empty except for the top level working groups table. The Descpub admin and analysis coordinator have the ability to populate the tables.
