### ISSUE TITLE
Make separate page for DESC members to join or leave a project

### ISSUE THREAD

**Issue by chee999** [LSSTDESC/desc-publications#73]
Currently only the publication admin and project leads can add/remove members of a project. Make a page that lists all the available projects with checkboxes next to each project so a member can add or remove themselves.

**Comment by sethdigel** [comment]
This would be ok but I think that the approach described in #79 is enough.  People typically will not join Projects very often - it is a long-term commitment - and typically will join them one at a time.

**Comment by sethdigel** [comment]
I'm going to close this issue.  People will sign on to projects one at a time.
