### ISSUE TITLE
Project participants

### ISSUE THREAD

**Issue by sethdigel** [LSSTDESC/desc-publications#79]
* On the page for a project, e.g., http://portal.lsstdesc.org/Pubs/projectView.jsp?projid=86&swgid=4
we need a way for DESC members to add themselves or remove themselves from the list of participants in the project.  

* Also, the list of participants should be shown on  the project page.  

* It would be extremely useful if the system could also generate a mailto:  link with e-mail addresses of all project participants

**Comment by sethdigel** [comment]
Charlotte and I discussed the first bulleted item above.  Because project membership is kept track of by the Group Manager, she suggested adding a link from the page for a Project directly to  the Group manager page for that Project, where the user could add or remove him or herself.

**Comment by chee999** [comment]
When a member leaves a project then they should also be removed from any papers under the project? If any requests for authorship were made these would also be removed?

**Comment by sethdigel** [comment]
Good questions.   The answers are no.  It certainly isn't worth making these kinds of consistency checks.  Also, it is entirely possible that a DESC member who is not nominally signed up for a Project could end up being a co-author on a paper in that Project.

**Comment by sethdigel** [comment]
Also, the page for a Project should list who has signed up for the Project, or include a link a page where the list is available.   If it is a list of people, I'd recommend putting it at the end.  

If it is possible to include a mailto: link to contact everyone signed up for the Project, that would be useful.

**Comment by chee999** [comment]
Note to myself (Chee): Membership in a project should be controlled by desc-members group, any DESC member can join or leave at will. Project leads control creating projects.

**Comment by sethdigel** [comment]
Charlotte has implemented all three of the requested features.  Thank you, Charlotte!
