### ISSUE TITLE
Updates to / questions about working group pages

### ISSUE THREAD

**Issue by rmandelb** [LSSTDESC/desc-publications#8]
Here are some comments on the working group pages, which I got to by going to http://portal.lsstdesc.org/Pubs/ and then clicking on the names of working groups:

- I don't really understand the meaning of the "Candidates" and "Conveners" lists that you can join/leave.  Can you please explain?

- It's great that you can see all projects associated with the working group in one place.  Would it be possible to also show a list of all *papers* associated with the group?  For example, some projects have no papers (yet), others might have 2-3.  Since it's not a 1:1 mapping and sometimes what we care about are papers, it seems like having both a project list and a paper list would be helpful.

**Comment by chee999** [comment]
The labels 'Conveners' and 'Candidates' have been removed. There are links now to all the projects and all the publications.

**Comment by sethdigel** [comment]
* In the Large Scale Structure Working Group page http://portal.lsstdesc.org/Pubs/show_swg.jsp?swgid=2&swgname=Large%20Scale%20Structure, I am given the option to add and remove conveners.  The conveners normally would change only every year or so.  I am not sure how they are currently being updated in the DESC database, but if there already is a way that this is done, then I don't think we need to have an additional way here.  I'd recommend just listing the names of the conveners (including links to their e-mail addresses).

* For what it is worth, when I added Michel Wood-Vasey as a convener here and clicked 'Join' I got taken to an updated version of the page that listed him in the right-hand column, but the title of the working group was gone from the heading of the page; it just said 'Science Working Group:'.

* On this page, I'd recommend placing the table of Project on top, above the list of members of the group and the conveners.

* I'd recommend including a link to the archives of the e-mail list of the working group.  That said, I'm not having any luck finding archives.  From this page, http://srs.slac.stanford.edu/GroupManager/exp/LSST-DESC/protected/mailLists.jsp, if I click on the link for the Weak Lensing archive, for example I am asked for my e-mail address and password, then told that either the archive does not exist or that I am not allowed to see it.  Also, the Large Scale Structure group does not even seem to have an archive link.

**Comment by rmandelb** [comment]
The username/password for the mailing list archives is not your own; there's a generic one for the collaboration described here: https://confluence.slac.stanford.edu/display/LSSTDESC/List+of+Mailing+Lists

I've had issues in the past where it has sometimes expired with nobody noticing, and had to be updated, but usually that works for me.

**Comment by rmandelb** [comment]
@chee999 - now I'm no longer seeing the new navigation options at the top, and the changes you said were done do not appear (e.g., I don't see papers at the bottom of WG pages, but you said in the comment today that you had added it).  Is it possible that somehow it's showing an older version of the system rather than the latest?

**Comment by sethdigel** [comment]
> The username/password for the mailing list archives is not your own; there's a generic one for the collaboration described here: https://confluence.slac.stanford.edu/display/LSSTDESC/List+of+Mailing+Lists

Thank you, Rachel.  I had no idea.  It seems awkward, but I guess there's a reason it works this way.

**Comment by chee999** [comment]
These issues have been addressed.
