### ISSUE TITLE
Project journal papers

### ISSUE THREAD

**Issue by sethdigel** [LSSTDESC/desc-publications#80]
If a Project (e.g., http://portal.lsstdesc.org/Pubs/projectView.jsp?projid=86&swgid=4) has any associated journal papers, I’d recommend listing them first in the table of documents, or in a separate table that appears first on the page, so they are always easy to find.

**Comment by chee999** [comment]
All the documents associated with a project should be listed with the project. Should journal papers have a separate display?

**Comment by sethdigel** [comment]
I don't think they need a separate display.  If you can force them to be listed first in the table of documents, that would be fine (and the preferable option).  Otherwise I'd vote for having journal papers in a separate table that appears first - as noted above.

**Comment by chee999** [comment]
The display has been updated to list Journal papers first.

**Comment by sethdigel** [comment]
Thank you!
