### ISSUE TITLE
Adding documents to a Project

### ISSUE THREAD

**Issue by sethdigel** [LSSTDESC/desc-publications#86]
From the page listing the Projects in a WG, e.g., http://portal.lsstdesc.org/Pubs/show_swg.jsp?swgid=4, I see an 'Add document' column.  That's fine, but I think it would be intuitive to also include an 'Add document' link on the page that lists the documents in a Project, like http://portal.lsstdesc.org/Pubs/projectView.jsp?projid=86&swgid=4

**Comment by chee999** [comment]
'Add document' link has been added to the page that lists the documents in projectView.jsp.

**Comment by sethdigel** [comment]
Thank you, Charlotte.  I'm not seeing that yet.  Does that mean  the change has not been  'deployed' yet?

<img width="541" alt="project_view" src="https://user-images.githubusercontent.com/6035835/42717302-e65181f8-86b4-11e8-8c44-777a25f6bc89.png">

**Comment by sethdigel** [comment]
For what it is worth, I'm still not seeing it in the newly deployed version.

**Comment by chee999** [comment]
How about now?

**Comment by sethdigel** [comment]
No, I'm afraid not.  I see the list of documents, but no button for adding another.

**Comment by chee999** [comment]
and now?

**Comment by sethdigel** [comment]
Still no, I'm afraid.  I do not see an Add Document button in either Dev or Prod. 

<img width="622" alt="project_docs" src="https://user-images.githubusercontent.com/6035835/43112092-2ece4b18-8ea9-11e8-9ab7-a64eca471afd.png">

 (I do see 'Add Project' on the page that lists the Projects in a WG.)

**Comment by chee999** [comment]
I see the Add link in the image you sent. Does clicking on 'Add' not work?

**Comment by sethdigel** [comment]
Ah!  I was looking for a button, like the Create Project button.  What you have implemented works fine, although if it is easy, a button would be harder to miss for users.

**Comment by sethdigel** [comment]
(Documenting an earlier discussion with Charlotte) Charlotte pointed out that a button would still have to appear within the 'frame' of the box.  She was going to try it to see whether the formatting broke or it looked odd as a result.

**Comment by chee999** [comment]
Documents may or may not belong to a project but they must associated with a working group.

**Comment by sethdigel** [comment]
I think that this can be closed.  Thank you.  The 'Authorized tasks' box makes the link for adding a document easy to spot.
