### ISSUE TITLE
Internal server error adding an internal reviewer

### ISSUE THREAD

**Issue by sethdigel** [LSSTDESC/desc-publications#88]
For this document in the Dev server
http://portal.lsstdesc.org/Pubs/editLink.jsp?paperid=130
when I select a name from the list of potential internal reviewers and click 'Join' I get a page with "500 - Internal server error.  There is a problem with the resource you are looking for, and it cannot be displayed."

**Comment by chee999** [comment]
I'd like to delete all the records in dev because some of the information was already removed.

**Comment by sethdigel** [comment]
Yes, please go ahead - sounds like it will solve the problem

**Comment by chee999** [comment]
the data in the dev tables has been deleted.
