### ISSUE TITLE
Some extraneous groups in Group Manager

### ISSUE THREAD

**Issue by sethdigel** [LSSTDESC/desc-publications#89]
I had occasion to look at my entry in the User-Group Manager tonight, http://srs.slac.stanford.edu/GroupManager/exp/LSST-DESC/protected/user.jsp?memidnum=815&recType=INDB

It lists several groups that I am not part of that I think are meant to be hidden as part of the Pub Management system, e.g., paper_181, paper_leads_181, project_181, etc.  Actually, probably these groups should go away since they were related to testing.

**Comment by chee999** [comment]
This has been cleaned up.
