### ISSUE TITLE
Reset document number and project ID counters in the Prod system? 

### ISSUE THREAD

**Issue by sethdigel** [LSSTDESC/desc-publications#90]
Can we reset these to 1 in the Prod system (after clearing the tables)?  This would be cleaner than starting in the hundreds or whatever we got up to in the Dev system.

**Comment by chee999** [comment]
This brings up a good point - the profile_ug and profile_group tables will also have to be updated. There is no good way to reset Oracle sequences short of dropping a sequence then re-creating it.

**Comment by chee999** [comment]
The dev table sequences have been reset. A side-effect is all the links in github issues no longer have anything to point to. Not a big loss since it's only development.
