### ISSUE TITLE
Updating link to the Publication Policy

### ISSUE THREAD

**Issue by sethdigel** [LSSTDESC/desc-publications#91]
In the 'DESC Publication Board' pull-down menu, the link to the Pub Policy should point to http://lsst-desc.org/sites/default/files/LSST_DESC_Publication_Policy.pdf
The same is true for the link to the Pub Policy on this page:  http://portal.lsst-desc.org/?experiment=LSST-DESC

These links should then never need updating (unless/until lsst-desc.org gets revamped) because new versions of the Pub Policy will always be put in the same place, with the same file name.

**Comment by chee999** [comment]
The link has been updated
