### ISSUE TITLE
Required fields when creating a document entry

### ISSUE THREAD

**Issue by sethdigel** [LSSTDESC/desc-publications#92]
In filling out the Document Details form for a 'Journal paper', the system is requiring me to provide entries for the 'arXiv', 'Published_reference', 'DOI', and 'ADS' fields.  None of these are known when a paper is first being drafted and so they should be optional.

**Comment by sethdigel** [comment]
And I'm afraid that when I made phony entries for those fields and hit the Create Document button, I got an error message.

Error. Failed to create document: Cluster surprises in DC2: a new analysis
Parent key is 2
CurrSequence:
javax.servlet.jsp.JspException: insert into descpub_publication (status,key_paper,builder_eligible,state,can_request_authorship,confluence_url,short_title,arxiv,title,ads,doi,published_reference,passed_internal_review,paperid,project_id,createdate,createdby,pubtype) values (?,?,?,?,?,?,?,?,?,?,?,?,?,DESCPUB_PUB_SEQ.nextval,?,sysdate,?,?) : ORA-00904: "CONFLUENCE_URL": invalid identifier
PARAM=submit=Create Document Entry
PARAM=status=Internal
PARAM=key_paper=Standard
PARAM=builder_eligible=N
PARAM=state=created
PARAM=can_request_authorship=N
PARAM=projid=2
PARAM=swgid=4
PARAM=pubtype=Journal paper
PARAM=confluence_url=https://confluence.slac.stanford.edu/display/LSSTDESC/Publication+Board
PARAM=authcontacts=748:Alexandra Abate:alexabate
PARAM=formsubmitted=true
PARAM=short_title=DC2 Clusters
PARAM=arxiv=abc
PARAM=summary rows=20 cols=80 required=breakthroughs from DC2
PARAM=title=Cluster surprises in DC2: a new analysis
PARAM=ads=jkl
PARAM=doi=ghi
PARAM=published_reference=def
PARAM=passed_internal_review=N

**Comment by chee999** [comment]
Sorry - I was fiddling with the tables. Can you try again?

Chee

**Comment by sethdigel** [comment]
Thanks a lot, Charlotte.  It works fine for me, and it did not make me fill in those fields.
