### ISSUE TITLE
Banner Heading for 'Project'

### ISSUE THREAD

**Issue by sethdigel** [LSSTDESC/desc-publications#93]
The pull-down menus across the  top of each  page have a heading  called  'Project'.  I'd like to ask that it  be changed to something like 'LSST Project'.  And moved all the way to the left.  I'd be happier  if it were removed.  'Project' has an entirely different meaning in  the DESC Pub System and having a 'Project' heading next to 'DESC Publication Board' is potentially confusing.

**Comment by chee999** [comment]
Swapped 'Project' with 'Standing Meetings' but did not rename 'Project' since it is the key used to map menu items. Is this ok?

**Comment by sethdigel** [comment]
Thank you, Charlotte.  I can't say it is ideal but it is certainly a big improvement, and good enough.
