### ISSUE TITLE
Ghost projects

### ISSUE THREAD

**Issue by sethdigel** [LSSTDESC/desc-publications#94]
In the Prod system the list on the index.jsp page shows two Projects.  On the all_projects page, four more Projects appear, with no WG connection.  I think that they are left over from an earlier era.  Just noting them here in case it is a real issue.

<img width="910" alt="all_projects" src="https://user-images.githubusercontent.com/6035835/42717531-8cc5d222-86b6-11e8-905f-39b88dd46c84.png">

**Comment by sethdigel** [comment]
We'll want to reset (clear?) the Prod tables and document  counters once more when the system  is ready to go in any case.

**Comment by chee999** [comment]
As a test, I set the ghost projects 'Inactive' which is the current way to remove a project from view. Seems to work so far. I agree, before going public all the data and sequences should be reset.

**Comment by sethdigel** [comment]
Ok, thanks.  The projects are still appearing on all_projects page.  If that is your intent, ok.  But I think it could be confusing eventually when we have projects labeled inactive.

**Comment by chee999** [comment]
This is only fixed in the development version. Once I deploy the changes to production the inactive projects will not show up.

**Comment by sethdigel** [comment]
Great!  Thank you, Charlotte.
