### ISSUE TITLE
Uploading a new version of a document does not seem to work

### ISSUE THREAD

**Issue by sethdigel** [LSSTDESC/desc-publications#97]
This feature seems to be broken for me,  e.g., on this page:
http://portal.lsstdesc.org/Pubs/uploadPub.jsp?paperid=4

When I try to upload a new version, I get a Server Error message after a whilel

**Comment by chee999** [comment]
This might be a browser issue. I was unable to upload anything using the Firefox browser but I was able to upload files using the Opera browser. Tony also was able to upload via the Chrome browser.

**Comment by sethdigel** [comment]
Interesting.  The equivalent still does not work for me on Firefox and it also does not work on Safari.

That is, uploads through this service do not work for me:
http://portal.lsstdesc.org/Pubs/upload.jsp 

Uploads from pages like this:
http://portal.lsstdesc.org/Pubs/show_pub.jsp?paperid=3
**do** work.

**Comment by chee999** [comment]
The url should be uploadPub.jsp.

Chee

**Comment by sethdigel** [comment]
Charlotte fixed the code to point at the correct URL.
