### ISSUE TITLE
URL for a DESC Project

### ISSUE THREAD

**Issue by sethdigel** [LSSTDESC/desc-publications#99]
In the URL for a  DESC Project, e.g., 
http://portal.lsstdesc.org/Pubs/projectView.jsp?projid=221&swgid=4
is the '&swgid=4' part essential?  That is, doesn't the project ID uniquely define the project?  (I'm asking because of the possibility of taking advantage of a URL shortener to point at specific DESC Projects.)

**Comment by chee999** [comment]
The swgid is essential only if the working group has to be known for some reason.  Since I wasn't sure I just passed it along.

**Comment by sethdigel** [comment]
Ok, good.  Actually, now that I check, I see that this URL works:
http://portal.lsstdesc.org/Pubs/projectView.jsp?projid=221
(i.e., the absence of '&swgid=4' does not matter.  That is what I hoped.
